controller_manager:
  ros__parameters:
    update_rate: 100  

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    slider_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    rm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


slider_position_controller:
  ros__parameters:
    joints:
      - slider_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    gains: 
      p: 200.0
      i: 0.1
      d: 10.0


rm_group_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    interpolation_method: splines  
