controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    column_position_controller:
      type: forward_command_controller/ForwardCommandController
      joints:
        - linear_guide_prismatic_joint
      interface_name: position
